---
- name: Include Add repository tasks for "{{ ansible_distribution }}"
  include_tasks: "{{ ansible_distribution }}.yml"
  when: wtd_repo_mariadb_enabled

- name: Add key for repository MariaDB
  rpm_key:
    state: present
    key: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
  when: wtd_repo_mariadb_enabled

- name: Include cleanup tasks
  include_tasks: cleanup.yml
  when: not wtd_repo_mariadb_enabled
