---
- name: "Include Add repository tasks for {{ ansible_distribution }}"
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Add key for repository MariaDB
  rpm_key:
    state: present
    key: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
