---
- name: "Fail if MariaDB version is not supported on {{ ansible_distribution }}"
  fail:
    msg: "MariaDB version {{ wtd_repo_mariadb_version }} is not supported on {{ ansible_distribution }}. See https://downloads.mariadb.org/mariadb/repositories/"
  when: wtd_repo_mariadb_version not in wtd_repo_mariadb_supported_versions_redhat

- name: Add repository MariaDB
  yum_repository:
    name: mariadb
    description: MariaDB
    file: MariaDB
    baseurl: "http://yum.mariadb.org/{{ wtd_repo_mariadb_version }}/rhel{{ansible_distribution_major_version }}-amd64"
    gpgcheck: yes
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
  register: wtd_repo_mariadb_added

- name: Refresh yum metadata if repository MariaDB was added
  command: yum makecache fast
  args:
    warn: no
  when: wtd_repo_mariadb_added.changed
